# Generated by Django 4.0.3 on 2022-05-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserNameF', models.CharField(max_length=122)),
                ('EmailF', models.EmailField(blank=True, max_length=254)),
                ('PasswordF', models.CharField(max_length=122)),
            ],
        ),
    ]
