# Generated by Django 4.0.3 on 2022-05-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signinapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signdb',
            name='UserNameF',
        ),
        migrations.AlterField(
            model_name='signdb',
            name='EmailF',
            field=models.EmailField(max_length=122),
        ),
    ]
